///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace SpeedTests
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the SpeedTestsRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "7.0")]
    [RepositoryFolder("f576162f-f336-45e8-b069-ccfbe6b9efbc")]
    public partial class SpeedTestsRepository : RepoGenBaseFolder
    {
        static SpeedTestsRepository instance = new SpeedTestsRepository();
        SpeedTestsRepositoryFolders.SnapXUntitledAppFolder _snapxuntitled;
        SpeedTestsRepositoryFolders.OpenSnapXRoutineAppFolder _opensnapxroutine;
        SpeedTestsRepositoryFolders.ElapsedTimeOnePRTNotepadAppFolder _elapsedtimeoneprtnotepad;
        SpeedTestsRepositoryFolders.ElapsedTimeTwoPRTNotepadAppFolder _elapsedtimetwoprtnotepad;
        SpeedTestsRepositoryFolders.ElapsedTimeThreePRTNotepadAppFolder _elapsedtimethreeprtnotepad;
        SpeedTestsRepositoryFolders.ElapsedTimeFourPRTNotepadAppFolder _elapsedtimefourprtnotepad;
        SpeedTestsRepositoryFolders.ElapsedTimeFivePRTNotepadAppFolder _elapsedtimefiveprtnotepad;

        /// <summary>
        /// Gets the singleton class instance representing the SpeedTestsRepository element repository.
        /// </summary>
        [RepositoryFolder("f576162f-f336-45e8-b069-ccfbe6b9efbc")]
        public static SpeedTestsRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public SpeedTestsRepository() 
            : base("SpeedTestsRepository", "/", null, 0, false, "f576162f-f336-45e8-b069-ccfbe6b9efbc", ".\\RepositoryImages\\SpeedTestsRepositoryf576162f.rximgres")
        {
            _snapxuntitled = new SpeedTestsRepositoryFolders.SnapXUntitledAppFolder(this);
            _opensnapxroutine = new SpeedTestsRepositoryFolders.OpenSnapXRoutineAppFolder(this);
            _elapsedtimeoneprtnotepad = new SpeedTestsRepositoryFolders.ElapsedTimeOnePRTNotepadAppFolder(this);
            _elapsedtimetwoprtnotepad = new SpeedTestsRepositoryFolders.ElapsedTimeTwoPRTNotepadAppFolder(this);
            _elapsedtimethreeprtnotepad = new SpeedTestsRepositoryFolders.ElapsedTimeThreePRTNotepadAppFolder(this);
            _elapsedtimefourprtnotepad = new SpeedTestsRepositoryFolders.ElapsedTimeFourPRTNotepadAppFolder(this);
            _elapsedtimefiveprtnotepad = new SpeedTestsRepositoryFolders.ElapsedTimeFivePRTNotepadAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("f576162f-f336-45e8-b069-ccfbe6b9efbc")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The SnapXUntitled folder.
        /// </summary>
        [RepositoryFolder("fba33c25-8c4b-40d7-9138-93af7c3ad7b6")]
        public virtual SpeedTestsRepositoryFolders.SnapXUntitledAppFolder SnapXUntitled
        {
            get { return _snapxuntitled; }
        }

        /// <summary>
        /// The OpenSnapXRoutine folder.
        /// </summary>
        [RepositoryFolder("1b207ee9-47bc-4776-9e09-babd5b1318ab")]
        public virtual SpeedTestsRepositoryFolders.OpenSnapXRoutineAppFolder OpenSnapXRoutine
        {
            get { return _opensnapxroutine; }
        }

        /// <summary>
        /// The ElapsedTimeOnePRTNotepad folder.
        /// </summary>
        [RepositoryFolder("3df79756-6573-4060-af5c-1c0b3eb9011b")]
        public virtual SpeedTestsRepositoryFolders.ElapsedTimeOnePRTNotepadAppFolder ElapsedTimeOnePRTNotepad
        {
            get { return _elapsedtimeoneprtnotepad; }
        }

        /// <summary>
        /// The ElapsedTimeTwoPRTNotepad folder.
        /// </summary>
        [RepositoryFolder("09023e9a-b1bd-440d-879f-fff7ee22b169")]
        public virtual SpeedTestsRepositoryFolders.ElapsedTimeTwoPRTNotepadAppFolder ElapsedTimeTwoPRTNotepad
        {
            get { return _elapsedtimetwoprtnotepad; }
        }

        /// <summary>
        /// The ElapsedTimeThreePRTNotepad folder.
        /// </summary>
        [RepositoryFolder("85e82a84-9beb-4e52-9c12-45640b70140f")]
        public virtual SpeedTestsRepositoryFolders.ElapsedTimeThreePRTNotepadAppFolder ElapsedTimeThreePRTNotepad
        {
            get { return _elapsedtimethreeprtnotepad; }
        }

        /// <summary>
        /// The ElapsedTimeFourPRTNotepad folder.
        /// </summary>
        [RepositoryFolder("a252e5ec-a091-4ba1-b59e-5cc7023b851a")]
        public virtual SpeedTestsRepositoryFolders.ElapsedTimeFourPRTNotepadAppFolder ElapsedTimeFourPRTNotepad
        {
            get { return _elapsedtimefourprtnotepad; }
        }

        /// <summary>
        /// The ElapsedTimeFivePRTNotepad folder.
        /// </summary>
        [RepositoryFolder("ac83621c-6291-4e3f-872e-5fc266d25644")]
        public virtual SpeedTestsRepositoryFolders.ElapsedTimeFivePRTNotepadAppFolder ElapsedTimeFivePRTNotepad
        {
            get { return _elapsedtimefiveprtnotepad; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "7.0")]
    public partial class SpeedTestsRepositoryFolders
    {
        /// <summary>
        /// The SnapXUntitledAppFolder folder.
        /// </summary>
        [RepositoryFolder("fba33c25-8c4b-40d7-9138-93af7c3ad7b6")]
        public partial class SnapXUntitledAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _element94Info;
            RepoItemInfo _buttonokInfo;
            RepoItemInfo _remeasureInfo;
            RepoItemInfo _finishInfo;

            /// <summary>
            /// Creates a new SnapXUntitled  folder.
            /// </summary>
            public SnapXUntitledAppFolder(RepoGenBaseFolder parentFolder) :
                    base("SnapXUntitled", "/form[@title='Snap-X - [Untitled]']", parentFolder, 500000, null, true, "fba33c25-8c4b-40d7-9138-93af7c3ad7b6", "")
            {
                _element94Info = new RepoItemInfo(this, "Element94", "element[@controlid='94']", 500000, null, "76c8b8ce-92bd-450a-8977-236f63e76e7d");
                _buttonokInfo = new RepoItemInfo(this, "ButtonOK", "container/form//button[@text='&OK']", 500000, null, "f7b05518-65b8-4d1a-b3d0-ef4b40182a53");
                //_remeasureInfo = new RepoItemInfo(this, "ReMeasure", "container/form/?/?/element/element/container/button[@text='Re-Measure' and @enabled='True']", 1000000, null, "fdde19aa-2930-49b2-b57f-e7ed19b7f556");
                _remeasureInfo = new RepoItemInfo(this, "ReMeasure", "container[@controlid='59648']//button[@text='Re-Measure' and @enabled='True']", 300000, null, "00e03edc-fc5a-42dd-a45a-0ef737982254");
                //_finishInfo = new RepoItemInfo(this, "Finish", "container/form/?/?/element/element/container/button[@text='Finish' and @enabled='True']", 1000000, null, "5274fe14-9b92-4e07-9dbc-ece5afef7527");
                _finishInfo = new RepoItemInfo(this, "Finish", "container[@controlid='59648']//button[@text='Finish' and @enabled='True']", 300000, null, "b11eaeb2-faaa-46af-998b-14a7402099c8");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("fba33c25-8c4b-40d7-9138-93af7c3ad7b6")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("fba33c25-8c4b-40d7-9138-93af7c3ad7b6")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The TitleBar item.
            /// </summary>
            [RepositoryItem("76c8b8ce-92bd-450a-8977-236f63e76e7d")]
            public virtual Ranorex.Unknown Element94
            {
                get
                {
                    return _element94Info.CreateAdapter<Ranorex.Unknown>(true);
                }
            }

            /// <summary>
            /// The Element94 item info.
            /// </summary>
            [RepositoryItemInfo("76c8b8ce-92bd-450a-8977-236f63e76e7d")]
            public virtual RepoItemInfo Element94Info
            {
                get
                {
                    return _element94Info;
                }
            }

            /// <summary>
            /// The ButtonOK item.
            /// </summary>
            [RepositoryItem("f7b05518-65b8-4d1a-b3d0-ef4b40182a53")]
            public virtual Ranorex.Button ButtonOK
            {
                get
                {
                    return _buttonokInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The ButtonOK item info.
            /// </summary>
            [RepositoryItemInfo("f7b05518-65b8-4d1a-b3d0-ef4b40182a53")]
            public virtual RepoItemInfo ButtonOKInfo
            {
                get
                {
                    return _buttonokInfo;
                }
            }

            /// <summary>
            /// The ReMeasure item.
            /// </summary>
            [RepositoryItem("00e03edc-fc5a-42dd-a45a-0ef737982254")]
            public virtual Ranorex.Button ReMeasure
            {
                get
                {
                    return _remeasureInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The ReMeasure item info.
            /// </summary>
            [RepositoryItemInfo("00e03edc-fc5a-42dd-a45a-0ef737982254")]
            public virtual RepoItemInfo ReMeasureInfo
            {
                get
                {
                    return _remeasureInfo;
                }
            }

            /// <summary>
            /// The Finish item.
            /// </summary>
            [RepositoryItem("b11eaeb2-faaa-46af-998b-14a7402099c8")]
            public virtual Ranorex.Button Finish
            {
                get
                {
                    return _finishInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Finish item info.
            /// </summary>
            [RepositoryItemInfo("b11eaeb2-faaa-46af-998b-14a7402099c8")]
            public virtual RepoItemInfo FinishInfo
            {
                get
                {
                    return _finishInfo;
                }
            }
        }

        /// <summary>
        /// The OpenSnapXRoutineAppFolder folder.
        /// </summary>
        [RepositoryFolder("1b207ee9-47bc-4776-9e09-babd5b1318ab")]
        public partial class OpenSnapXRoutineAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _filenamefieldInfo;

            /// <summary>
            /// Creates a new OpenSnapXRoutine  folder.
            /// </summary>
            public OpenSnapXRoutineAppFolder(RepoGenBaseFolder parentFolder) :
                    base("OpenSnapXRoutine", "/form[@title='Open Snap-X Routine']", parentFolder, 30000, null, true, "1b207ee9-47bc-4776-9e09-babd5b1318ab", "")
            {
                _filenamefieldInfo = new RepoItemInfo(this, "FileNameField", "?/?/text[@controlid='1148']", 30000, null, "4ffde906-5caa-4e1f-9916-cde343dfc1a1");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("1b207ee9-47bc-4776-9e09-babd5b1318ab")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("1b207ee9-47bc-4776-9e09-babd5b1318ab")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The FileNameField item.
            /// </summary>
            //[RepositoryItem("4ffde906-5caa-4e1f-9916-cde343dfc1a1")]
            //public virtual Ranorex.Text FileNameField
            //{
            //    get
            //    {
            //        return _filenamefieldInfo.CreateAdapter<Ranorex.Text>(true);
            //    }
            //}

            /// <summary>
            /// The FileNameField item info.
            /// </summary>
            [RepositoryItemInfo("4ffde906-5caa-4e1f-9916-cde343dfc1a1")]
            public virtual RepoItemInfo FileNameFieldInfo
            {
                get
                {
                    return _filenamefieldInfo;
                }
            }
        }

        /// <summary>
        /// The ElapsedTimeOnePRTNotepadAppFolder folder.
        /// </summary>
        [RepositoryFolder("3df79756-6573-4060-af5c-1c0b3eb9011b")]
        public partial class ElapsedTimeOnePRTNotepadAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _text15Info;

            /// <summary>
            /// Creates a new ElapsedTimeOnePRTNotepad  folder.
            /// </summary>
            public ElapsedTimeOnePRTNotepadAppFolder(RepoGenBaseFolder parentFolder) :
                    base("ElapsedTimeOnePRTNotepad", "/form[@title~'^ElapsedTimeOne\\.PRT\\ -\\ Note']", parentFolder, 30000, null, true, "3df79756-6573-4060-af5c-1c0b3eb9011b", "")
            {
                _text15Info = new RepoItemInfo(this, "Text15", "text[@controlid='15']", 30000, null, "f2ef2c69-f0e7-4e31-ae76-6155a6c3d5f2");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("3df79756-6573-4060-af5c-1c0b3eb9011b")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("3df79756-6573-4060-af5c-1c0b3eb9011b")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Text15 item.
            /// </summary>
            [RepositoryItem("f2ef2c69-f0e7-4e31-ae76-6155a6c3d5f2")]
            public virtual Ranorex.Text Text15
            {
                get
                {
                    return _text15Info.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Text15 item info.
            /// </summary>
            [RepositoryItemInfo("f2ef2c69-f0e7-4e31-ae76-6155a6c3d5f2")]
            public virtual RepoItemInfo Text15Info
            {
                get
                {
                    return _text15Info;
                }
            }
        }

        /// <summary>
        /// The ElapsedTimeTwoPRTNotepadAppFolder folder.
        /// </summary>
        [RepositoryFolder("09023e9a-b1bd-440d-879f-fff7ee22b169")]
        public partial class ElapsedTimeTwoPRTNotepadAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _text15Info;

            /// <summary>
            /// Creates a new ElapsedTimeTwoPRTNotepad  folder.
            /// </summary>
            public ElapsedTimeTwoPRTNotepadAppFolder(RepoGenBaseFolder parentFolder) :
                    base("ElapsedTimeTwoPRTNotepad", "/form[@title~'^ElapsedTimeTwo\\.PRT\\ -\\ Note']", parentFolder, 30000, null, true, "09023e9a-b1bd-440d-879f-fff7ee22b169", "")
            {
                _text15Info = new RepoItemInfo(this, "Text15", "text[@controlid='15']", 30000, null, "011d1101-5bec-43a3-bc04-83467971ab65");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("09023e9a-b1bd-440d-879f-fff7ee22b169")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("09023e9a-b1bd-440d-879f-fff7ee22b169")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Text15 item.
            /// </summary>
            [RepositoryItem("011d1101-5bec-43a3-bc04-83467971ab65")]
            public virtual Ranorex.Text Text15
            {
                get
                {
                    return _text15Info.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Text15 item info.
            /// </summary>
            [RepositoryItemInfo("011d1101-5bec-43a3-bc04-83467971ab65")]
            public virtual RepoItemInfo Text15Info
            {
                get
                {
                    return _text15Info;
                }
            }
        }

        /// <summary>
        /// The ElapsedTimeThreePRTNotepadAppFolder folder.
        /// </summary>
        [RepositoryFolder("85e82a84-9beb-4e52-9c12-45640b70140f")]
        public partial class ElapsedTimeThreePRTNotepadAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _text15Info;

            /// <summary>
            /// Creates a new ElapsedTimeThreePRTNotepad  folder.
            /// </summary>
            public ElapsedTimeThreePRTNotepadAppFolder(RepoGenBaseFolder parentFolder) :
                    base("ElapsedTimeThreePRTNotepad", "/form[@title~'^ElapsedTimeThree\\.PRT\\ -\\ No']", parentFolder, 30000, null, true, "85e82a84-9beb-4e52-9c12-45640b70140f", "")
            {
                _text15Info = new RepoItemInfo(this, "Text15", "text[@controlid='15']", 30000, null, "87a0d916-3bd5-45c0-b37c-dae91a1ea035");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("85e82a84-9beb-4e52-9c12-45640b70140f")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("85e82a84-9beb-4e52-9c12-45640b70140f")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Text15 item.
            /// </summary>
            [RepositoryItem("87a0d916-3bd5-45c0-b37c-dae91a1ea035")]
            public virtual Ranorex.Text Text15
            {
                get
                {
                    return _text15Info.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Text15 item info.
            /// </summary>
            [RepositoryItemInfo("87a0d916-3bd5-45c0-b37c-dae91a1ea035")]
            public virtual RepoItemInfo Text15Info
            {
                get
                {
                    return _text15Info;
                }
            }
        }

        /// <summary>
        /// The ElapsedTimeFourPRTNotepadAppFolder folder.
        /// </summary>
        [RepositoryFolder("a252e5ec-a091-4ba1-b59e-5cc7023b851a")]
        public partial class ElapsedTimeFourPRTNotepadAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _text15Info;

            /// <summary>
            /// Creates a new ElapsedTimeFourPRTNotepad  folder.
            /// </summary>
            public ElapsedTimeFourPRTNotepadAppFolder(RepoGenBaseFolder parentFolder) :
                    base("ElapsedTimeFourPRTNotepad", "/form[@title~'^ElapsedTimeFour\\.PRT\\ -\\ Not']", parentFolder, 30000, null, true, "a252e5ec-a091-4ba1-b59e-5cc7023b851a", "")
            {
                _text15Info = new RepoItemInfo(this, "Text15", "text[@controlid='15']", 30000, null, "ec3ba7dd-1a67-4b87-b4a8-f67d9f145c8b");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("a252e5ec-a091-4ba1-b59e-5cc7023b851a")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("a252e5ec-a091-4ba1-b59e-5cc7023b851a")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Text15 item.
            /// </summary>
            [RepositoryItem("ec3ba7dd-1a67-4b87-b4a8-f67d9f145c8b")]
            public virtual Ranorex.Text Text15
            {
                get
                {
                    return _text15Info.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Text15 item info.
            /// </summary>
            [RepositoryItemInfo("ec3ba7dd-1a67-4b87-b4a8-f67d9f145c8b")]
            public virtual RepoItemInfo Text15Info
            {
                get
                {
                    return _text15Info;
                }
            }
        }

        /// <summary>
        /// The ElapsedTimeFivePRTNotepadAppFolder folder.
        /// </summary>
        [RepositoryFolder("ac83621c-6291-4e3f-872e-5fc266d25644")]
        public partial class ElapsedTimeFivePRTNotepadAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _text15Info;

            /// <summary>
            /// Creates a new ElapsedTimeFivePRTNotepad  folder.
            /// </summary>
            public ElapsedTimeFivePRTNotepadAppFolder(RepoGenBaseFolder parentFolder) :
                    base("ElapsedTimeFivePRTNotepad", "/form[@title~'^ElapsedTimeFive\\.PRT\\ -\\ Not']", parentFolder, 30000, null, true, "ac83621c-6291-4e3f-872e-5fc266d25644", "")
            {
                _text15Info = new RepoItemInfo(this, "Text15", "text[@controlid='15']", 30000, null, "1246af0d-069d-470f-a2a6-714bdb44d84b");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("ac83621c-6291-4e3f-872e-5fc266d25644")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("ac83621c-6291-4e3f-872e-5fc266d25644")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Text15 item.
            /// </summary>
            [RepositoryItem("1246af0d-069d-470f-a2a6-714bdb44d84b")]
            public virtual Ranorex.Text Text15
            {
                get
                {
                    return _text15Info.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Text15 item info.
            /// </summary>
            [RepositoryItemInfo("1246af0d-069d-470f-a2a6-714bdb44d84b")]
            public virtual RepoItemInfo Text15Info
            {
                get
                {
                    return _text15Info;
                }
            }
        }

    }
#pragma warning restore 0436
}